### ISSUE TITLE
Add as a new branch

### ISSUE THREAD

**Issue by AcaiBerii** [Crystallinqq/osu-2005#1]
Save repo waste make branch in osu repo

**Comment by Crystallinqq** [comment]
too lazy

**Comment by Crystallinqq** [comment]
do it urself

**Comment by AcaiBerii** [comment]
I am now angry and my day has been ruined.

**Comment by Crystallinqq** [comment]
Good.

**Comment by Crystallinqq** [comment]
why r u reversing kants rat. its been reversed as of years ago 😹

**Comment by AcaiBerii** [comment]
aw i didnt know :(
